# Generated by Django 4.2.21 on 2026-06-07 16:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherprofile',
            name='experience_years',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='middle_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.CreateModel(
            name='TeacherAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='teacher_achievements/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_achievements', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Достижение учителя',
                'verbose_name_plural': 'Достижения учителя',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='StudentAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(blank=True, upload_to='student_achievements/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_achievements', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Достижение ученика',
                'verbose_name_plural': 'Достижения учеников',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='QualificationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('awarded_date', models.DateField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Квалификационная категория',
                'verbose_name_plural': 'Квалификационные категории',
                'ordering': ['-awarded_date'],
            },
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('institution', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='diplomas/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Диплом',
                'verbose_name_plural': 'Дипломы',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('file', models.FileField(upload_to='certificates/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='profiles.teacherprofile')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-start_date'],
            },
        ),
    ]
