# Generated by Django 4.2.21 on 2026-06-08 20:20

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_teacherprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='file',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='student_achievements/'),
        ),
        migrations.AlterField(
            model_name='teacherachievement',
            name='file',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='teacher_achievements/'),
        ),
    ]
