# Generated by Django 4.2.21 on 2026-06-08 20:50

from django.db import migrations, models
import profiles.storage


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_certificate_file_alter_diploma_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='file',
            field=models.FileField(storage=profiles.storage.PublicRawStorage(), upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='diploma',
            name='file',
            field=models.FileField(storage=profiles.storage.PublicRawStorage(), upload_to='diplomas/'),
        ),
        migrations.AlterField(
            model_name='studentachievement',
            name='file',
            field=models.FileField(blank=True, storage=profiles.storage.PublicRawStorage(), upload_to='student_achievements/'),
        ),
        migrations.AlterField(
            model_name='teacherachievement',
            name='file',
            field=models.FileField(blank=True, storage=profiles.storage.PublicRawStorage(), upload_to='teacher_achievements/'),
        ),
    ]
